### PR TITLE
Improved starmap secondary fuel circle

### PR DESCRIPTION
**Pull request by taleden**
The description of MegaMod's secondary "point of no return" fuel range circle implies (at least to me) that it shows how far one could travel from the current position and still have enough fuel to return from that waypoint to Sol (A -> B -> Sol). But the way it was implemented, that was only true when the current position was in Sol itself; from anywhere else, what it *actually* showed was the range one could travel and still have fuel to first return to the current location, and then from there back to Sol (A -> B -> A -> Sol). But that's not a route that's usually of much interest.

Thinking more about the underlying math, a true "point of no return" range ought to be not a circle but an ellipse, with its two focii at Sol and the current location, and its "sum of radii" equal to the total fuel range. Unfortunately the code can currently only draw axis-aligned ellipses (used for planetary orbit lines); rasterizing an ellipse with an arbitrary rotation is somewhat trickier and would require a whole new drawing function.

So instead, I simply changed the secondary fuel circle to originate from the current autopilot destination, and show the range remaining after traveling there. By setting a waypoint and seeing if Sol still lies inside the secondary circle, this can still provide the same "point of no return (to Sol)" information, but is also more flexible: for example, it can tell you whether you can fly to some place and then get from there to the nearest supergiant star to refuel with the Melnorme instead.

I also changed the "select" button behavior on the starmap so that if you re-set the autopilot destination again to exactly the same coordinates, it instead clears the waypoint. This incidentally makes it easy to toggle that secondary fuel circle on and off to see how it looks. :)

If merged, the Setup help strings would also need to be updated. I can make a separate PR on the Content project for that if necessary, or you can just rephrase those two lines and commit directly. :)

### CODE REVIEW

**Comment by Serosis** [comment]
You _technically_ don't need new functions to create an arbitrarily rotated ellipse.

You create the ellipse using DrawFilledOval() then use RotateFrame() to angle it. At least in theory.

I'll check out this PR when I get some time and think about it.

**Comment by taleden** [comment]
Ah, didn't realize that was an option. Personally I ended up like this approach better anyway since it's not limited to measuring against Sol, but if you prefer a static ellipse I can look into doing it that way.

**Comment by Serosis** [comment]
I'll take a look a bit later at this PR and see if I like it.

**Comment by Serosis** [comment]
Oh I see what it does now. It shows how much range you'll have left if you travel that distance.
That could be a useful secondary option on top of Sol Range.
Maybe as a separate toggle even.

I want to wait now and see if you think it's feasible to do the Sol Ellipse. 
Otherwise I'd like to implement this, perhaps with some different color shades, as a new option.

EDIT:
Would the option sound like "Destination Fuel Range" or "Fuel Range at Destination"?

**Comment by taleden** [comment]
I've worked out the math for calculating the position, size, and rotation of a Sol fuel range ellipse, but I'm not at all familiar with UQM's graphics system so I couldn't see how to get `DrawFilledOval()` to draw into a specific frame which I could then `RotateFrame()` before drawing onto the starmap. Any suggestions where in the code to look for an example of how to do this? Is there a way to `SetContext()` to some arbitrary buffer rather than a specific area of the screen?

**Comment by Serosis** [comment]
Crap. The "DrawOvals" do not draw to frame but draw a series of lines.
I guess one *would* have to find another way to create a new FRAME just for the oval.

Sorry about that.

EDIT:

I'm now thinking that maybe DrawFilledOval could be modified, using maths, to angle it before it's drawn...
But it's just an idea, I'm so crap at maths that I would have to take a month off just to figure that out.

**Comment by taleden** [comment]
I tried creating a 128x128 circle sprite (tacked onto the end of MiscDataFrame) and using that; it kind of works, except transparency data is getting lost somewhere so it deletes a box from the regular fuel circle, and the scaling/rotating isn't super high quality so the edges of the resulting ellipse look rough, with lots of resampling artifacts:
uqm-mm-ellipse
All around not a great solution, I think. Adding or changing the circle drawing code to support a skew (which is effectively a rotation, for an ellipse) would get better results, but I'm not sure I'm up for figuring out that math either.

**Comment by Serosis** [comment]
This idea may have to be put on the backburner for now.

I'm avoiding taking deep looks into the code currently but I'm fairly certain there is a way to draw an ellipse without jumping through hoops or rescaling images.

Something to do with the contexts you mentioned earlier, pulling the FRAME data out of there... I think.

Maybe we can find a maths formula for drawing an ellipse in SDL and apply it to the setup UQM uses?

**Comment by taleden** [comment]
Even if `DrawFilledOval()` could be easily modified to draw to a `FRAME` to then use `RotateFrame()`, I suspect the result still wouldn't look great; the edges would look rough and imprecise, especially compared to the pixel-perfect edge of the regular fuel circle on screen at the same time.

I think the best options would either be to write a completely separate version of `DrawFilledOval()` using a different algorithm that can rasterize an ellipse with arbitrary rotation, or else modify the existing `DrawFilledOval()` to be able to apply a "shear" during drawing, and then work out the math for the right position, size, and shear values to produce an equivalent shape to the desired rotated ellipse.

I don't think I'll have the bandwidth for either of those in the near future, but I'd be happy to make other smaller tweaks to this range-from-destination feature. For example, I made a related change to the bubble warp feature which triggers the warp when exiting the starmap with a waypoint set, rather than immediately upon setting the waypoint; that way you have the opportunity to see the range-from-destination first, and can decide whether to cancel the waypoint before committing to the warp.

**Comment by Serosis** [comment]
Yeah I was thinking the same thing, a new function that can draw what you want without having to modify existing frames.

Also, should not a point of no return graphic be teardrop shaped, not oval?

And the idea for bubble warp sounds neat, though I'd have to test it out to be sure if I liked it.

**Comment by taleden** [comment]
To clarify, "bubble warp" is already an existing option in MegaMod's "cheats" menu, I just changed how it works slightly. Before, with that setting enabled, you could never see your autopilot route or destination on the starmap because the instant you set a destination, you'd warp there and be booted from the starmap; now you can set your destination and see the range-at-destination circle as normal, and the warp doesn't happen until you exit the starmap yourself.

What makes you say teardrop? I'm pretty sure it would have to be an ellipse, unless we're thinking of a different definition of point of no return.

**Comment by Serosis** [comment]
> To clarify, "bubble warp" is already an existing option in MegaMod's "cheats" menu, I just changed how it works slightly. Before, with that setting enabled, you could never see your autopilot route or destination on the starmap because the instant you set a destination, you'd warp there and be booted from the starmap; now you can set your destination and see the range-at-destination circle as normal, and the warp doesn't happen until you exit the starmap yourself.

I understood that, I just meant I'd have to play around with it to see if it gets in my way. I kinda like the instant transport.  
How about a compromise, if _Infinite Fuel_ is enabled it happens as soon as you hit "Enter" but otherwise it works normally, where you have to exit the StarMap.

> What makes you say teardrop? I'm pretty sure it would have to be an ellipse, unless we're thinking of a different definition of point of no return.

Maybe I'm over thinking or thinking about it wrong but shouldn't the half-circle directly away from Sol stay the same shape while it gradually closes into a point over Sol?
The half-circle in question.
image

**Comment by taleden** [comment]
> I understood that, I just meant I'd have to play around with it to see if it gets in my way. I kinda like the instant transport. How about a compromise, if _Infinite Fuel_ is enabled it happens as soon as you hit "Enter" but otherwise it works normally, where you have to exit the StarMap.

Oh, gotcha. Yeah, that could work, though personally I think my vote would be to favor consistency of behavior rather than working differently when combined with Infinite Fuel just for the sake of saving a single keystroke. Having it delay until exiting the Starmap also offers greater consistency with the interaction flow when not using Bubble Warp at all: when you set an autopilot destination the Starmap doesn't close by default, you still have to close it manually (with a single keystroke) before the ship starts navigating on autopilot.

> Maybe I'm over thinking or thinking about it wrong but shouldn't the half-circle directly away from Sol stay the same shape while it gradually closes into a point over Sol?

I don't think so. Consider that if your current total fuel range `R` exceeds your distance from Sol `D`, then you could fly directly away from Sol as far as `(R - D) / 2` before having to turn around and fly directly to Sol; but if you were to fly to Sol first, you'd still have the same amount `R - D` of remaining fuel range, which means you could fly past Sol as far as `(R - D) / 2` before having to turn around again. So we know the "point of no return" area should not end on Sol, but should rather extend past Sol exactly as far as it extends away from Sol in the opposite direction.

To visualize it another way, have you ever done the experiment where you put two pins/nails/whatever in a paper, put a loop of string around both of them, and then pull the loop of string taut with a pencil and trace the arc you can draw all the way around? The resulting shape is an ellipse with its two foci at the pins (representing Sol and current location) and the length of string representing total fuel range.

[Here's a visualization](https://www.mathsisfun.com/geometry/ellipse.html) where you can imagine F is current position, G is Sol, and P is any place you could fly to from F and still have exactly enough fuel to get home to G; FP+PG = total fuel range.

**Comment by Serosis** [comment]
I made an alternative function to draw an ellipse based off [12oclocker's](https://stackoverflow.com/a/47766167) answer on a StackOverflow question.

https://github.com/Serosis/UQM-MegaMod/commit/1d757f0621daf06577443198c44845395e144a90

Probably don't need the unfilled version but it exists regardless.

I'm thinking perhaps this could be the start of a new function that can draw an angled ellipse since it's just a bit easier to read than UQM's own built in functions.

**Comment by taleden** [comment]
It's definitely easier to read, and this angle-sweep approach makes sense for relatively efficiently drawing an un-filled ellipse using line segments, but for the purpose of rasterizing a filled ellipse I suspect a Bresenham-esque scan-line approach would be faster and possibly also easier to modify to accept a shear parameter (which will be needed to simulate drawing a non-axis-aligned ellipse).

[Here's an example of this algorithm](https://stackoverflow.com/a/49526656); if I have some time this weekend I may try implementing it with a shear.

**Comment by Serosis** [comment]
Actually the code I modified for the filled ellipse portion is a sort of scanline approach by quadrant.

I left the outline code in as a sort of goof since UQM's DrawOval compensates for the thicker lines in HD.

**Comment by taleden** [comment]
This problem kept nagging at me so I ended up staying up way too late last night [tracking down and implementing the formulas](https://zingl.github.io/Bresenham.pdf) (from sections 2.1 and 4.3, specifically) to convert a rotated ellipse into a shreared axis-aligned ellipse, and to efficiently draw an axis-aligned ellipse with a shear value, either filled or outlined, and optionally dotted.

Voila:
uqm-mm-ellipse2

I used the lighter filled shading for the point-of-no-return ellipse (since that represents something about your actual range from the current position) and changed the range-from-destination circle to a dotted outline (since it represents a hypothetical range, were you to travel there first).

Right now they're both toggled by the same options setting, but I suppose they should probably be split up either into two separate toggles, or a four-way setting (default, sol-range, destination-range, both). The code could also be optimized a bit more, although the performance difference would hardly matter on any modern system; I suppose an RPi or something might benefit.

**Comment by Serosis** [comment]
Dude, you are a beast.

If you like I can handle making the options.

**Pull request merged**
