### PR TITLE
Add SDL2 support (ported from 0.7.1 branch)

### PR DESCRIPTION
**Pull request by Ala-lala**
This PR adds support for SDL2 based on the code from 0.7.1. It currently has two issues that I know of, however:
1. Both 0.7.0-2 and 0.7.1 changed how Mac builds work, and new libraries that this depends on (SDL2 and libpng) were added after some of these changes. I don't know how to add them "the old way" since I don't have any experience with Mac builds or even a Mac to test it on. For this reason, I've merged the changes that 0.7.1 made to Mac builds (or at least I tried to - again, I can't test it). The issue with this is that standalone (i.e. not dependent on libraries from brew) builds are, from what I know, currently impossible in 0.7.1, pending a fix before it is released.
2. Android build is completely untested. I wouldn't be surprised if some of the Android-specific input code is broken with SDL2.

Notes:
* **Four of the patches that I made for this are also applicable to base 0.7.1:** 172c3f4 (critical), 54e983b (major), c8c8201 (minor *as long as* `SDL_GetRendererInfo` succeeds), and c56b4fc (minor).
* MinGW can currently only build with SDL2 because the build script doesn't support SDL being in its own directory under `LIBRARY_PATH`.
* I've removed the NoAccel configurations from the VS2008 and VS2019 projects and replaced them with SDL1 configurations (they aren't really needed anymore AFAIK and I didn't want to make NoAccel configurations for both SDL1 and SDL2).
* I built the libpng DLL with VS2008 because I couldn't get it to build in VS2019, but it seems to work fine in VS2019 too.
*  All scalers seem to work fine in HD with SDL2 (though HQ is unplayably slow for me), so I've changed the setup menu code to let you use them (on SDL2).
* Gamma correction does not work with SDL2, so I've hidden the slider in the setup menu (on SDL2).

### CODE REVIEW

**Comment by Serosis** [comment]
Wait... This works with HD mode as well?

This is massive. 

I was planning on doing this whole thing where I'd set up a new fork of UQM 0.7.1 and start layering the MegaMod on top of it one feature at a time so that there would be a proper commit history.

I think I'm going to be giving you more than just a programming credit.

MegaMod (Ala-lala Edition) or something like that.

**Comment by Ala-lala** [comment]
As far as I can tell, yep, it works fine. I ran into surprisingly few incompatibilites between the 0.7.1 and HD code.

**Comment by Serosis** [comment]
Quick question not too off-topic:

How did you merge mcmartin's changes onto the MegaMod while keeping his history?

EDIT:

~In regards to Android compatibility the commandergenius Android SDL port has SDL2 support so I don't expect there to be too many roadblocks.~

EDIT Again:

Scratch that. I'm going to see if I can use Visual Studio's built in Android support to spit out a port.

**Comment by Ala-lala** [comment]
I have very little experience with Git, so I don't know if this was the best way or not, but I just generated patches for all of the commits (with `git format-patch`), fetched the base repository in my MegaMod repository so that merges would work, then applied them one by one with `git am -3 -p2` (`-p2` since everything in the MegaMod is under `sc2/` in base UQM).

**Comment by Serosis** [comment]
Another question, if you had an avatar would it be a Supox as your namesake suggests?

What I'm thinking of doing is adding a little graphic to the main menu at the top-right corner with the text "Ala-lala Edition" at a 45 degree angle below/next to it.

***Or***... Add your screen name to the logo graphic with mine so it reads "Serosis & Ala-lala Presents"

Though if you could think of anything else or if you just don't want that kind of special call-out throw out a suggestion.

Especially after merging SDL2 into the MegaMod, I thought that was going to be one of my month-long projects in the future.

**Comment by Serosis** [comment]
An update on Android compatibility. All I had to do was explicitly define SDL_MAJOR_VERSION to 1 in the config_unix.h that's unique to the Android build and it compiles and runs just as it has before.

Well, it was a bit more involved than that, I also had to tell the build script to ignore the new SDL2 specific files and include libpng.

**Pull request merged**
